const domainModel = Object.freeze({
    QuestionnaireModel:0,
    SectionModel:1,
    SectionModel_MappedFromQuestionnaireId:2,
    QuestionModel:3,
    QuestionChoiceModel:4,
    UserModel_MappedFromUserId:5,
    UserModel_MappedFromUserViewModel:6,
    RoleModel_MappedFromRoleDtoModel:7,
    UserRoleModel:8,
    RegisterModel:9,
    SessionModel:10,
    CookieObjectModel:11,
    SessionDomainModel_MappedFromSessionDtoModel:12,
    SessionViewModel_MappedFromSessionDtoModel:13,
    ResponseStatementModel_MappedFromResponseStatementId:14,
    ResponseStatementModel_MappedFromResponseStatementViewModel:15,
    ResponseModel_MappedFromResponseViewModel:16,
    0:'QuestionnaireModel',
    1:'SectionModel',
    2:'SectionModel_MappedFromQuestionnaireId',
    3:'QuestionModel',
    4:'QuestionChoiceModel',
    5:'UserModel_MappedFromUserId',
    6:'UserModel_MappedFromUserViewModel',
    7:'RoleModel_MappedFromRoleDtoModel',
    8:'UserRoleModel',
    9:'RegisterModel',
    10:'SessionModel',
    11:'CookieObjectModel',
    12:'SessionDomainModel_MappedFromSessionDtoModel',
    13:'SessionViewModel_MappedFromSessionDtoModel',
    14:'ResponseStatementModel_MappedFromResponseStatementId',
    15:'ResponseStatementModel_MappedFromResponseStatementViewModel',
    16:'ResponseModel_MappedFromResponseViewModel'
});

module.exports = domainModel;